rel

diff --git a/Dockerfile.release b/Dockerfile.release
--- a/Dockerfile.release
+++ b/Dockerfile.release
@@ -127,7 +127,7 @@ COPY --link lib lib
 # RUN ls -la assets/static
 
 # workaround for compilation errors (eg. "could not load module Needle.UID due to reason :unavailable")
-RUN MIX_ENV=prod mix deps.clean needle_uid jason poison --build
+RUN MIX_ENV=prod mix deps.clean needle_uid jason poison bonfire --build
 RUN MIX_ENV=prod mix deps.compile --include-children needle_uid needle_ulid paper_trail
 
 # compile protocols (attempted fix for 'could not load module Poison.Encoder due to reason :unavailable')
@@ -167,7 +167,7 @@ RUN MIX_ENV=prod CI=1 mix phx.digest
 RUN ls -la priv/static
 RUN ls -la priv/static/assets
 
-RUN tar --exclude=*.env --exclude=.git --exclude=node_modules --exclude=priv/static/source.tar.gz  --exclude=priv/static/data --exclude=*/*/assets/static/data -czvf priv/static/source.tar.gz lib deps apps extensions forks config docs priv/repo priv/static mix.exs mix.lock LICENSE || echo "Could not prepare code archive"
+RUN tar --exclude=*.env --exclude=.git --exclude=node_modules --exclude=priv/static/source.tar.gz  --exclude=priv/static/data --exclude=*/*/assets/static/data --exclude=deps/*/cache -czvf priv/static/source.tar.gz lib deps apps extensions forks config docs priv/repo priv/static mix.exs mix.lock LICENSE || echo "Could not prepare code archive"
 
 # build final OTP release
 RUN MIX_ENV=prod CI=1 mix release
