archive

diff --git a/Dockerfile.release b/Dockerfile.release
--- a/Dockerfile.release
+++ b/Dockerfile.release
@@ -124,12 +124,15 @@ RUN MIX_ENV=prod mix deps.clean needle_ulid jason poison --build
 # compile app (needs to be before building assets so it includes Surface hooks & component CSS)
 RUN MIX_ENV=prod mix compile
 
+# generate exdocs so they can be included in the code archive
+RUN MIX_ENV=prod mix docs
+
 # Include any migrations provided by flavour (maybe not needed?)
 # COPY --link data/current_flavour/repo priv/repo
 RUN mkdir -p priv/repo/migrations
 
 # Copy DB/repo migrations from installed extensions
-RUN mix bonfire.extension.copy_migrations --force --to priv/repo/migrations
+RUN MIX_ENV=prod mix bonfire.extension.copy_migrations --force --to priv/repo/migrations
 
 # docs/guides
 COPY --link LICENSE ./
@@ -150,7 +153,7 @@ RUN MIX_ENV=prod CI=1 mix phx.digest
 RUN ls -la priv/static
 RUN ls -la priv/static/assets
 
-RUN tar --exclude=*.env --exclude=.git --exclude=node_modules --exclude=priv/static/data --exclude=*/*/assets/static/data -czvf priv/static/source.tar.gz lib deps apps extensions forks config docs priv/repo priv/static mix.exs mix.lock LICENSE || echo "Could not prepare code archive"
+RUN tar --exclude=*.env --exclude=.git --exclude=node_modules --exclude=priv/static/source.tar.gz  --exclude=priv/static/data --exclude=*/*/assets/static/data -czvf priv/static/source.tar.gz lib deps apps extensions forks config docs priv/repo priv/static mix.exs mix.lock LICENSE || echo "Could not prepare code archive"
 
 # build final OTP release
 RUN MIX_ENV=prod CI=1 mix release
